"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const {clone,fixture} = require("./test_helpers");
const {validateAcquisitionResult}=require("../validators/validate_acquisition_result");
const {validateCandidateSource}=require("../validators/validate_candidate_source");
const {validateStructuredEvidence}=require("../validators/validate_structured_evidence");
const {validateEvidenceBatch}=require("../validators/validate_evidence_batch");
const {validateScannerResult}=require("../validators/validate_scanner_result");

function values(){const candidates=fixture("no_signal","candidate_sources"),evidences=fixture("no_signal","structured_evidence"),scanner=fixture("no_signal","scanner_result");return{candidates,evidences,scanner,evidence:evidences[0],ctx:{taskId:scanner.taskId,executionId:scanner.executionId,candidates,evidences}};}
function assertInvalid(call,code,path){let out;assert.doesNotThrow(()=>{out=call();});assert.equal(out.valid,false);assert(out.errors.some((e)=>e.code===code&&e.path===path));return out;}

test("evidence rejects null candidate context entry",()=>{const v=values();assertInvalid(()=>validateStructuredEvidence(v.evidence,{...v.ctx,candidates:[null]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");});
test("evidence rejects string candidate context entry",()=>{const v=values();assertInvalid(()=>validateStructuredEvidence(v.evidence,{...v.ctx,candidates:["x"]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");});
test("evidence rejects empty candidate context entry",()=>{const v=values();assertInvalid(()=>validateStructuredEvidence(v.evidence,{...v.ctx,candidates:[{}]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");});
test("evidence rejects numeric candidate context entry",()=>{const v=values();assertInvalid(()=>validateStructuredEvidence(v.evidence,{...v.ctx,candidates:[42]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");});
test("evidence rejects candidate missing sourceId",()=>{const v=values(),bad=clone(v.candidates[0]);delete bad.sourceId;assertInvalid(()=>validateStructuredEvidence(v.evidence,{...v.ctx,candidates:[bad]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");});
test("evidence rejects candidate missing task or execution",()=>{const v=values(),a=clone(v.candidates[0]),b=clone(v.candidates[0]);delete a.taskId;delete b.executionId;assertInvalid(()=>validateStructuredEvidence(v.evidence,{...v.ctx,candidates:[a]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");assertInvalid(()=>validateStructuredEvidence(v.evidence,{...v.ctx,candidates:[b]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");});

test("batch rejects malformed candidate with zero counters and bytes",()=>{const v=values(),out=assertInvalid(()=>validateEvidenceBatch(v.evidences,{...v.ctx,candidates:[null]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");assert.equal(out.acceptedEvidenceCount,0);assert.equal(out.rejectedEvidenceCount,0);assert.equal(out.totalVisibleTextBytes,0);});
test("batch rejects null evidence without throwing",()=>{const v=values(),out=validateEvidenceBatch([null],v.ctx);assert.equal(out.valid,false);assert.equal(out.rejectedEvidenceCount,1);assert.equal(out.totalVisibleTextBytes,0);assert(out.errors.some((e)=>e.code.startsWith("SCHEMA_")));});
test("batch rejects primitive evidence without throwing",()=>{const v=values();let out;assert.doesNotThrow(()=>{out=validateEvidenceBatch([7],v.ctx);});assert.equal(out.valid,false);assert.equal(out.rejectedEvidenceCount,1);assert.equal(out.totalVisibleTextBytes,0);});
test("batch catches injected evidence validator exception",()=>{const evidencePath=require.resolve("../validators/validate_structured_evidence"),batchPath=require.resolve("../validators/validate_evidence_batch"),saved=require.cache[evidencePath].exports;try{require.cache[evidencePath].exports={validateStructuredEvidence(){throw new Error("RAW_INTERNAL_MESSAGE");}};delete require.cache[batchPath];const injected=require("../validators/validate_evidence_batch");const v=values(),out=injected.validateEvidenceBatch(v.evidences,v.ctx);assert.equal(out.valid,false);assert(out.errors.some((e)=>e.code==="EVIDENCE_VALIDATION_EXCEPTION"));assert(!JSON.stringify(out).includes("RAW_INTERNAL_MESSAGE"));}finally{require.cache[evidencePath].exports=saved;delete require.cache[batchPath];require("../validators/validate_evidence_batch");}});

test("scanner rejects null and empty candidate entries",()=>{for(const entry of [null,{}]){const v=values(),out=assertInvalid(()=>validateScannerResult(v.scanner,{...v.ctx,candidates:[entry]}),"CONTEXT_CANDIDATE_INVALID","candidates[0]");assert.equal(out.acceptedFindingCount,0);assert.equal(out.rejectedFindingCount,0);}});
test("scanner rejects null and empty evidence entries",()=>{for(const entry of [null,{}]){const v=values(),out=assertInvalid(()=>validateScannerResult(v.scanner,{...v.ctx,evidences:[entry]}),"CONTEXT_EVIDENCE_INVALID","evidences[0]");assert.equal(out.acceptedFindingCount,0);assert.equal(out.rejectedFindingCount,0);}});
test("scanner rejects mixed valid and malformed candidate entries",()=>{const v=values();assertInvalid(()=>validateScannerResult(v.scanner,{...v.ctx,candidates:[v.candidates[0],null]}),"CONTEXT_CANDIDATE_INVALID","candidates[1]");});
test("scanner rejects mixed valid and malformed evidence entries",()=>{const v=values();assertInvalid(()=>validateScannerResult(v.scanner,{...v.ctx,evidences:[v.evidences[0],null]}),"CONTEXT_EVIDENCE_INVALID","evidences[1]");});

test("public validators contain unexpected proxy exceptions",()=>{const exploding=new Proxy({}, {get(){throw new Error("RAW_PROXY_SECRET");}}),v=values();for(const [call,code] of [[()=>validateAcquisitionResult(exploding),"SCHEMA_VALIDATION_EXCEPTION"],[()=>validateCandidateSource(v.candidates[0],exploding),"CANDIDATE_VALIDATION_EXCEPTION"],[()=>validateStructuredEvidence(v.evidence,exploding),"EVIDENCE_VALIDATION_EXCEPTION"],[()=>validateScannerResult(v.scanner,exploding),"SCANNER_VALIDATION_EXCEPTION"]]){let out;assert.doesNotThrow(()=>{out=call();});assert(out.errors.some((e)=>e.code===code));assert(!JSON.stringify(out).includes("RAW_PROXY_SECRET"));}});
test("batch outer boundary contains unexpected proxy exceptions",()=>{const v=values(),exploding=new Proxy(v.evidences,{get(target,key){if(key==="forEach")throw new Error("RAW_BATCH_SECRET");return Reflect.get(target,key);}}),out=validateEvidenceBatch(exploding,v.ctx);assert.equal(out.valid,false);assert.equal(out.errors[0].code,"EVIDENCE_BATCH_VALIDATION_EXCEPTION");assert.equal(out.acceptedEvidenceCount,0);assert(!JSON.stringify(out).includes("RAW_BATCH_SECRET"));});

test("malformed scanner contexts never throw",()=>{const v=values();for(const context of [{...v.ctx,candidates:[null]},{...v.ctx,candidates:["x"]},{...v.ctx,evidences:[null]},{...v.ctx,evidences:[42]},{...v.ctx,candidates:[v.candidates[0],{}]},{...v.ctx,evidences:[v.evidences[0],{}]}])assert.doesNotThrow(()=>validateScannerResult(v.scanner,context));});
test("context arrays and entries remain deeply equal",()=>{const v=values(),before=JSON.stringify(v.ctx);validateStructuredEvidence(v.evidence,v.ctx);validateEvidenceBatch(v.evidences,v.ctx);validateScannerResult(v.scanner,v.ctx);assert.equal(JSON.stringify(v.ctx),before);});
test("plain null-prototype context is accepted",()=>{const v=values(),context=Object.assign(Object.create(null),v.ctx);assert.equal(validateStructuredEvidence(v.evidence,context).valid,true);assert.equal(validateScannerResult(v.scanner,context).valid,true);});
