"use strict";
const test = require("node:test"); const assert = require("node:assert/strict");
const {clone, fixture} = require("./test_helpers");
const {validateStructuredEvidence} = require("../validators/validate_structured_evidence");
const {validateScannerResult} = require("../validators/validate_scanner_result");

function data(scenario) { const c = fixture(scenario, "candidate_sources"), e = fixture(scenario, "structured_evidence"), s = fixture(scenario, "scanner_result"); return {c, e, s, ec:{taskId:s.taskId,executionId:s.executionId,candidates:c},sc:{taskId:s.taskId,executionId:s.executionId,candidates:c,evidences:e}}; }
test("three fixture scenarios are semantically valid", () => { for (const scenario of ["no_signal", "synthetic_signal", "blocked"]) { const {e, s, ec, sc} = data(scenario); for (const value of e) assert.equal(validateStructuredEvidence(value, ec).valid, true); assert.equal(validateScannerResult(s, sc).valid, true); } });
test("unknown evidence reference is rejected", () => { const {s, sc} = data("synthetic_signal"); s.findings[0].evidenceReferences = ["f".repeat(64)]; assert(validateScannerResult(s, sc).errors.some((x) => x.code === "EVIDENCE_REFERENCE_NOT_FOUND")); });
test("blocked candidate cannot be analyzed or found", () => { const {c, s, sc} = data("blocked"); s.analyzedSourceIds = [c[0].sourceId]; s.findings = [{findingKey:"a".repeat(64),candidateId:c[0].sourceId,sourceUrl:c[0].canonicalUrl,signalType:"other",description:"Blocked source synthetic signal",severity:"low",confidence:0.2,evidenceReferences:[],requiresHumanReview:true,automatedConclusion:"suspected_signal"}]; const out = validateScannerResult(s, sc); assert(out.errors.some((x) => x.code === "ANALYZED_SOURCE_NOT_ACQUIRED")); assert(out.errors.some((x) => x.code === "FINDING_CANDIDATE_NOT_FOUND")); });
test("critical evidence and confidence rules", () => { const {s, sc} = data("synthetic_signal"); s.findings[0].severity = "critical"; s.findings[0].confidence = 0.7; s.findings[0].evidenceReferences = []; const out = validateScannerResult(s, sc); assert(out.errors.some((x) => x.code === "CRITICAL_EVIDENCE_REQUIRED")); assert(out.errors.some((x) => x.code === "CRITICAL_CONFIDENCE_LOW")); });
test("conclusive counterfeit language is rejected", () => { const {s, sc} = data("synthetic_signal"); s.findings[0].description = "Bu ürün kesin sahte olarak otomatik belirlenmiştir."; assert(validateScannerResult(s, sc).errors.some((x) => x.code === "CONCLUSIVE_COUNTERFEIT_LANGUAGE")); });
test("methodology without candidate/evidence is rejected", () => { const {s, sc} = data("synthetic_signal"); s.findings[0].candidateId = "f".repeat(64); s.findings[0].evidenceReferences = []; s.findings[0].description = "Bu örnek metodoloji şablonu gerçek bulgu değildir."; assert(validateScannerResult(s, sc).errors.some((x) => x.code === "METHODOLOGY_AS_FINDING")); });
test("duplicate finding key and fixture callback are rejected", () => { const {s, sc} = data("synthetic_signal"); s.findings.push(clone(s.findings[0])); sc.productionCallback=true; const out = validateScannerResult(s, sc); assert(out.errors.some((x) => x.code === "DUPLICATE_FINDING_KEY")); assert(out.errors.some((x) => x.code === "TEST_FIXTURE_PRODUCTION_CALLBACK")); });
test("total visible text budget is detectable", () => { const total = [131073,131073,131073].reduce((a,b)=>a+b,0); assert(total > 393216); });
